services:
  - type: web
    name: jueguitos-brainrot
    env: java
    buildCommand: mvn clean package
    startCommand: java -jar target/tallerwebi-base-1.0-SNAPSHOT.war
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jueguitos-db
          property: connectionString

databases:
  - name: jueguitos-db
    plan: free